
// Generated by bin/update-relationship-prompts.js. Recognition hashes only;
// obsolete instructions are retained solely in test fixtures, never sent to a model.
export const LEGACY_STATUS_SIGNATURES = {
    "prompt": {
        "d4e18f332df09bb366ccb5c941df000be851a4b94b3220a94f08245a4a60c431": "en",
        "a02b899da1f36077f8e8e8d4c484d3deb9527268cdd98adfa9345357084fd056": "de",
        "e507fd5c127354c92be8b7b76edb208cad9ce026ac1641e928f31644ecac4125": "es",
        "f53dc422756f70dfd300e85b9213f062bea7458ffbf1e5bfdd75c32efeaa0416": "fr",
        "492a134e32a4b1941d455bf4fa42a226901a217a9da33b591cfc20de6b90a1bd": "id",
        "b9841023938797c67c5c9269144c7559164e779f978cc515256792277b3b370f": "ja",
        "6c363389b64bae5781efd24509a03366980154d59897f45c4bc81639dbc8f94f": "ko",
        "1ac67302bc43f93872b645af9597c3f1959b9f0ec45b066632a3138d385f53d7": "ms",
        "21934b0eb4ee3fde21e4cd9c4248911020736c59563f7501ede25a101b13878b": "pt",
        "3703e235faf14981bbc092a8c1dda73fb4d510ebdbbcb939aee6ad1374f9f311": "ru",
        "aec9dd4ec22e1c68df693e25e7d6ccb049e121c1e9e61b2091219bf7b4112857": "zh-cn",
        "b64a6b196f70670e34fbb5143b201448144e6e35bfaa50a24f9e4800d7fd4f60": "zh-tw",
        "5fe0fcf590c3637bb7b6807fe4b5aeda0dab8728015b185388b921dcaa9d1881": "ja",
        "fbe9b2d49c4942072e425e4826250439d1dbc6b8c2d4c8bf7a6352e62b562477": "en"
    },
    "responseFormat": {
        "045c332b4e9eaf631f489ebbe82a1f484da7bcde33258d70c2e3b2bdceb4ed1f": "en",
        "bc69df65fa5c3368e64b68d2bb85bcae8da8d73b1b6753ce60786098ad670933": "de",
        "21e7dc92d09df6420a763328c93bbc3f216ffc6614d1582acc87022b6aee7d88": "es",
        "301786707c6169015a07cd4bfd03020a39ab2d3b79ab1aa3a255f4856f750a77": "fr",
        "266cb55e32c4838951dfee3e19bbf0d9c03891df26e65d3fab9c267a57ec7e29": "id",
        "982efd9ee9402c536eb34c59323eedf9f57ab4e935a977efbd11b703ed5e62c6": "ja",
        "d3c0e612995b1e5e2647f6aef3230a9662f88186a73ba47201fedf04ce32e43a": "ko",
        "f20fb78f4c40df171f7a8ef34437cd35aceb5787495786384a4cd1a3a82a1547": "ms",
        "973781c9cbdc354ecf30c0ff6a68255d76a1cb928a15aa6bbe274a1b950c8776": "pt",
        "5f8e87cd165e9bf5d70a5d8ea09fc76e4cc864ebf00cde489a80a19635653b65": "ru",
        "7b118e3c5d9abea933cd7a43db076d5ec99adc022d9fcbce3e576ade4a912b7f": "zh-cn",
        "7bf4d91ceeaad130f3adf1c32d12103a3938de70e1dfef29ba343ce610425921": "zh-tw",
        "c89369b7ad6427f0b4e7b09752b27e14e8318c95385fdb1ba4febb682142f400": "en"
    },
    "sections": {
        "d45a50f8b921e0e44948ea6a8f52854ecd36ebea59f941d070d69164f13ed595": {
            "locale": "en",
            "section": 0
        },
        "cbb81bd9ed899e2882df602130663e4eba50e6f9d82a0548ff2862249bca89d2": {
            "locale": "en",
            "section": 1
        },
        "d6f5a91206c33a91453d876c07fd425c2a390b22efb49b927ed4980430d5f628": {
            "locale": "en",
            "section": 2
        },
        "5a1af45c66ea6219592dcdcbea7e00110604a0799cde4b4b8fdf7dfd9700a402": {
            "locale": "en",
            "section": 4
        },
        "e91dfeaf14b46f8579c168d02fe82b819c60c97e1a7d60269c2f371514c74948": {
            "locale": "de",
            "section": 0
        },
        "ab6495461942e6b7cf6abbb6eb86daf72d6f5a5b551e09a1e9effc6079725c08": {
            "locale": "de",
            "section": 1
        },
        "0fe0944f2ac0522c4badaa093e048ff5205e591edbaa4592d7c41a6394a70d27": {
            "locale": "de",
            "section": 2
        },
        "ddcb13b2fd4898ec136cf8f05016585f140765081a6bd52088c95c8f0bd5dbb5": {
            "locale": "de",
            "section": 4
        },
        "53611bc2c131bb5d1a0744d9765db2d21d890c94d7f4bb487c3efee62d20bec6": {
            "locale": "es",
            "section": 0
        },
        "77ecd6f7c6b1b52b49c027c91ab408c90813fb5ce399a39e776fb5f289085848": {
            "locale": "es",
            "section": 1
        },
        "6385544782e23f91c5fb98b62ae4059075e153371ec77c8bfa0e5e91b7573ddf": {
            "locale": "es",
            "section": 2
        },
        "b131bf918fbece586a30f5a4549458e2f5ee4559b974539560c90448348a6d6c": {
            "locale": "es",
            "section": 4
        },
        "58847dfb76d9fa389d4979851319fe9bf5691f72ede289cbd68212f405e3f2f7": {
            "locale": "id",
            "section": 0
        },
        "288bed5cf10fa7211f38f0a5487f77737aaa24d4e488e45efd4fe3b2ee6440ce": {
            "locale": "id",
            "section": 1
        },
        "c33abfc5f4ecbaa671e22de6b34ed3ab0afbb17a2c6217ca6701071ef05c5b2b": {
            "locale": "id",
            "section": 2
        },
        "82f9acc9ca656d078f12a5793a0423e21d32a9fab9276fb4bcec47253da4482b": {
            "locale": "id",
            "section": 4
        },
        "445df5b949d8200bb9dfee2b6637cab102070a2e5e8586c37d0ddcec59f39a87": {
            "locale": "ja",
            "section": 0
        },
        "b3f387b8b5f184bde7697c3a39aa2f430283a035a4c5a358fbcdde97829cc6a2": {
            "locale": "ja",
            "section": 1
        },
        "07b395dab7b0db6d3e1f649e24d5da6ed7a93c3b7873be79e80bc3b2572d8bf5": {
            "locale": "ja",
            "section": 2
        },
        "145f8544944293a12d0f227acda119efb3df161e88baa10830e91aee412f1317": {
            "locale": "ja",
            "section": 4
        },
        "5d4a419d114811cd364e0e031b2a6c408e9d81b61fcac48bf1fdebd1a71bbbed": {
            "locale": "ko",
            "section": 0
        },
        "19518ee0c3b15236a289bf3559e9a44db10f8a39f56523b35d01af1fa4a3f2c3": {
            "locale": "ko",
            "section": 1
        },
        "441113d7032b5f23c6846f9f27dadc828b799dcca20ea3ecfd80de9a3911f802": {
            "locale": "ko",
            "section": 2
        },
        "99eb21981fcc55fd845108e2985d4b8b330fac29bf2f282b684ffd49e5217fa3": {
            "locale": "ko",
            "section": 4
        },
        "0927a2ae12aba553a4eac340eb7a67f2415cdbf4746b5cf24e272307e053cf6d": {
            "locale": "ms",
            "section": 0
        },
        "f06507490d2c3b2d61afd56a0405dffe43a5d03bf564388f69a0dfcef0e93467": {
            "locale": "ms",
            "section": 1
        },
        "5c9779fef06ef35f9a128c35abb2d1f094bdcf040f4001e56f7aee22db451850": {
            "locale": "ms",
            "section": 2
        },
        "a3502b751318d70c78f7ad95c0560e34e5e76b0ef6d7c660d566dff9a37fef87": {
            "locale": "ms",
            "section": 4
        },
        "a5a9477f2f4718858249329bae9605c290f86d1e11c7d7a3caa72c6fc14c481f": {
            "locale": "pt",
            "section": 0
        },
        "a73e0c7ace576922dfcb4ab9f3d79ed81f51c142e6c2759d45b02d7cd1a3643f": {
            "locale": "pt",
            "section": 1
        },
        "303a1cf13fd1d3268b9b18155b2b3b29defa020bc0a62c26b63bc589cfae9452": {
            "locale": "pt",
            "section": 2
        },
        "c7bacd46880d13016f84bc53afbf3232fd8703c09d04a689458c39fe22ab3f91": {
            "locale": "pt",
            "section": 4
        },
        "cf920c494a9cfeffc981544d5e06cf1dd0878114098b7d93290d0c75689b2ae1": {
            "locale": "ru",
            "section": 0
        },
        "8af899b2179021399be3e05c9321db5e23936aa4684a70e47e349629eef604fd": {
            "locale": "ru",
            "section": 1
        },
        "0841744941d162ecda39bc987ae46314417d03c6e60bd9e724ebe6f2fdda943c": {
            "locale": "ru",
            "section": 2
        },
        "1887c8182b8071300516ff5a564d3ae586a96423855448043d9cfbf1c854a198": {
            "locale": "ru",
            "section": 4
        },
        "a117e5343853baf4fc3866e44738b8d59e50eda2274ea8bf717f7d3a27a6268f": {
            "locale": "zh-cn",
            "section": 0
        },
        "9aac9bf1ed95a4c8187e64d132a88c43baffcfff356bfc4f567943e7cab6763a": {
            "locale": "zh-cn",
            "section": 1
        },
        "cb810ab2266f119a35279039aa1ef97712ce69d6c52d25d414770ccf253f2c9e": {
            "locale": "zh-cn",
            "section": 2
        },
        "c316bcc72d07a4868913bdf44384f700f35b990580a9b620bf40539115d5f2ee": {
            "locale": "zh-cn",
            "section": 4
        },
        "a28129a588fef6be72b363f3f98f2bae34a8707caf5c2029213146641c48d7cc": {
            "locale": "zh-tw",
            "section": 0
        },
        "15975e3c936b5ec06171bf84a3c6b44b6d2802a1d7d18f1dec819e395ec84d65": {
            "locale": "zh-tw",
            "section": 1
        },
        "2a8c6b124d9e2ceddf7039682a189673f9d4e67d756d06e763f45d3503889597": {
            "locale": "zh-tw",
            "section": 2
        },
        "154d816bb1308e54faa34a27d6e9200b3631cbfb04c0a52983172de3bb4fc087": {
            "locale": "zh-tw",
            "section": 4
        },
        "7eb48bd440034fc3262a6d21773ebe3a5bd650666118cbebe3fc73fd2998ecc3": {
            "locale": "en",
            "section": 0
        },
        "72693c019d4a6dbb034e75e0f4d71e3a2ba7d24f8e6914e4f7c124f1dadc736a": {
            "locale": "en",
            "section": 1
        },
        "a6e0bd683431b56b30819ad345ac30e06971041e7951bfc83804dcba8b6a5f0c": {
            "locale": "en",
            "section": -1
        }
    }
};
